version: '3.8'
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.100.2.0/24
services:
  tds-calculator_web:
    image: tds-calculator_web:latest
    command: ["uvicorn", "tds.calculator.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - /tmp:/data
    env_file:
      .env
    ports:
      - 8000:8000
